

def get_paragraph(package_name):

    dict = {
        'Australian Stocks':
        "Best Australian Stocks: This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'Low Price High Volume Stocks':
        "The High Volume Stocks Package is designed for investors and analysts who need predictions for stocks currently trading under ten dollars, and with an average daily trading volume above one million dollars. It includes stocks with bullish and bearish signals and indicates the best shares to buy and sell:",

        'High Volume Stocks':
        "The High Volume Stocks Package is designed for investors and analysts who need predictions for stocks currently trading between 5 and 30 dollars, and with an average daily trading volume above one million dollars. It includes stocks with bullish and bearish signals and indicates the best shares to buy and sell:",

        '52 Week High Stocks':
        "The 52 Week High Stocks Package is designed for investors and analysts who need predictions for stocks currently at their 52-week high price level. It includes stocks with bullish and bearish signals and indicates the best shares to buy and sell:",

        '52 Week Low Stocks':
        "The 52 Week Low Stocks Package is designed for investors and analysts who need predictions for stocks currently at their 52-week low price level, offering the best market opportunities based on algo-trading. It includes stocks with bullish and bearish signals and indicates the best stocks to invest in:",

        'Aggressive Stocks Forecast':
        "This forecast is part of the Risk-Conscious Package, as one of I Know First's equity research solutions. We determine our aggressive stock picks by screening our algorithm daily for higher volatility stocks that present greater opportunities but are also riskier. The full Risk-Conscious Package includes a daily forecast for a total of 40 stocks divided into four main categories:",

        'Automotive Stock Forecast':
        "This Automotive Stocks forecast is designed for investors and analysts who need predictions of the best-performing stocks in the automotive industry (see Automotive Stocks Package). It includes stocks with bullish and bearish signals and indicates the best auto stocks to trade:",

        'Bank Stock Forecast':
        "This forecast is designed for investors and analysts who need predictions of Bank Stocks (see Bank Stocks Package). It includes stocks with bullish and bearish signals and indicates the best bank stocks to trade:",

        'Basic Industry Forecast':
        "This Basic Industry forecast is designed for investors and analysts who need daily stock market predictions of the best-performing stocks for the whole Basic Industry (see Basic Industry Stocks Package). It includes stocks with bullish and bearish signals and indicates the best basic industry stocks to buy based on artificial intelligence:",

        'Biotech Stocks Forecast':
        "The BioTech Stocks Package is designed for investors and analysts who need predictions of the best stocks to buy for the whole Biotechnology Industry. It includes stocks with bullish and bearish signals and indicates the best biotech stocks to trade:",

        'Bitcoin':
        "The Bitcoin Package is designed for investors and analysts who need predictions of the best cryptocurrencies to buy. It includes 3 predictions with bullish and bearish signals and indicates the predicted direction in the given time horizon for the cryptocurrencies:",

        'Bovespa':
        "This Bovespa Stock forecast was generated by the I Know First Algorithm through its analysis of market data and is part of the By Country Package. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'Brazil Stock Forecast':
        "This Brazil Stock forecast was generated by the I Know First Algorithm through its analysis of market data and is part of the By Country Package. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'Canadian Stock Forecast':
        "This Canadian Stocks forecast is part of the By Country Package, as one of I Know First's systematic trading tools. The full forecast includes daily predictions for a total of top Canadian stocks with bullish and bearish signals:",

        'Chemicals Stocks':
        "This Chemicals Stocks forecast is designed for investors and analysts who need predictions of the best chemical stocks to buy for the whole Chemistry Industry (see Chemicals Stocks Package). It includes stocks with bullish and bearish signals and indicates the best chemical stocks to buy:",

        'Chinese Stock Forecast':
        "Top Performing Chinese Stocks: This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'Computer Industry':
        "The Computer Industry Stocks Package is designed for investors and analysts who need predictions of the best-performing stocks for the whole Computer Industry. It includes stocks with bullish and bearish signals and indicates the best stocks to buy in the computer industry:",

        'Conservative Stock Forecast':
        "This Conservative Stock forecast is part of the Risk-Conscious Package, as one of I Know First's quantitative investment solutions. We determine our best defensive stocks by screening our database daily for lower volatility stocks that are less risky. The full Risk-Conscious Package includes a daily forecast for a total of 40 stocks divided into four main categories:",

        'Consumer Stocks':
        "The Consumer Stocks Package is designed for investors and analysts who need predictions of the best performing stocks for the whole Consumer Industry. It includes stocks with bullish and bearish signals.",

        'Netherlands Stocks':
        "Best Dutch Stocks: This Netherlands Stock forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes a daily prediction for a total of stocks with bullish and bearish signals:",

        'Dividend Stocks Forecast':
        "This forecast is part of the Dividends Package, as one of I Know First's quantitative investment solutions. We determine the best stocks carrying a dividend by screening our database daily using our advanced algorithm.  The full Dividends Package includes a daily forecast for a total of stocks with bullish and bearish signals:",

        'Energy Stocks Forecast':
        "The Energy Stocks Package is based on the I Know First algorithm and is designed for investors and analysts who need recommendations for the best performing stocks for the whole Energy Industry. It includes stocks with bullish and bearish signals and indicates the best energy stocks to buy and sell:",

        'ETFs Forecast':
        "This forecast is part of the ETFs Package, as one of I Know First’s quantitative investment solutions. We determine the top ETFs by screening our database daily using our advanced algorithm. The full ETFs Package includes a daily forecast for a total of ETFs with bullish and bearish signals:",

        'European ETFs Forecast':
        "This forecast is part of the ETFs Package, as one of I Know First’s quantitative investment solutions. We determine the top ETFs by screening our database daily using our advanced algorithm. The full ETFs Package includes a daily forecast for a total of 20 ETFs with bullish and bearish signals:",

        'Chinese ETFs Forecast':
        "This forecast is part of the ETFs Package, as one of I Know First’s quantitative investment solutions. We determine the top ETFs by screening our database daily using our advanced algorithm. The full ETFs Package includes a daily forecast for a total of 20 ETFs with bullish and bearish signals:",

        'European Stock Forecast':
        "This European Stocks forecast is part of the By Region Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of best European stocks based on artificial intelligence with bullish and bearish signals:",

        'French Stock Forecast':
        "Best French Stocks: This French Stock forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes a daily prediction for a total of stocks with bullish and bearish signals:",

        'Fundamental':
        "The Fundamental Package includes our algorithmic forecasts for stocks screened by fundamental criteria. Our algorithms help you find best opportunities for both long and short positions for the stocks within each fundamental screen. The stocks are selected according to five basic valuation categories:",

        'German Stock Forecast':
        "Best German Stocks: This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'Japan Stock Forecast':
        "This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of Japanese stocks with bullish and bearish signals:",

        'Japan Stock Forecast':
        "This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of Nikkei 225 stocks with bullish and bearish signals:",

        'Russian Stock Forecast':
        "Best Russian Stocks: This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'Gold & Commodity Forecast':
        "This Commodities Package is designed for investors who need commodity recommendations to find the best performing commodities in the industry. It includes commodities with bullish or bearish signals indicating which are best to buy:",

        'Gold & Commodity Forecast':
        "This Commodity ETFs Package is designed for investors who need commodity recommendations to find the best performing commodity ETFs in the industry. It includes commodity ETFs with bullish or bearish signals indicating which are best to buy:",

        'Gold & Commodity Forecast':
        "This Commodity Futures Package is designed for investors who need commodity recommendations to find the best performing commodity futures in the industry. It includes commodity futures with bullish or bearish signals indicating which are best to buy:",

        'Gold & Commodity Forecast':
        "This Gold forecast is part of the Commodities Package, one of I Know First's algorithmic trading solutions. This package provides predictions for Gold and other precious metals for the various forecasted time frames and includes our algorithmic outlook for:",

        'Healthcare':
        "This Healthcare Stocks Package is designed for investors and analysts who need predictions of the best shares within the Healthcare Sector. It includes stocks with bullish and bearish signals and indicates the best healthcare stocks to buy and sell:",

        'Hedge Fund Stocks':
        "This Hedge Fund Stocks Package is designed for investors and analysts who need predictions of the best-performing stocks according to I Know First's stock market algorithm. It includes stocks with bullish and bearish signals and indicates the best stocks to long and short based on artificial intelligence trading strategies:",

        'Options':
        "This forecast is part of the Options Package, as one of I Know First's algorithmic trading tools. The full Top Options forecast includes daily predictions for the best options to buy for a total of stocks with bullish and bearish signals:",

        'Home Builders':
        "This Home Builders Stocks Package is designed for investors and analysts who need predictions of the best performing stocks for the whole Home Builders sector. It includes stocks with bullish and bearish signals and indicates the best Home Builders stocks to buy:",

        'Hong Kong Stock Forecast':
        "This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'Hong Kong Stock Forecast':
        "This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of Hong Kong stocks selected from MSCI index with bullish and bearish signals:",

        'Indian Stock Forecast':
        "Top Performing Indian Stocks: This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'Indices Forecast':
        "This stock market forecast is part of the World Indices Package, as one of I Know First's quantitative investment solutions. We determine our world indices forecast by screening our database daily using our advanced algorithm. The full World Indices Package includes a daily forecast for a total of indices with bullish and bearish signals:",

        'Indonesian Stocks':
        "Top Performing Indonesian Stocks: This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'Insider Trades':
        "An insider is legally permitted to buy and sell shares of the firm – and any subsidiaries – that employs him or her. However, these transactions must be properly registered with the Securities and Exchange Commission (SEC) and are done with advance filings. You can find details of this type of insider trading on the SEC's EDGAR database. This algorithmic forecast is for stocks with recently reported insiders' transactions. An 'insider' is any person who possesses at least one of the following:<ul><li>access to valuable non-public information about a corporation (for example a company's directors and high-level executives)</li><li>ownership of more than 10% of the company's equity</li></ul>",

        'Insurance Companies Forecast':
        "The Insurance Companies Package is designed for investors and analysts who need stock advice for the best-performing stocks in the Insurance Company Industry. It includes stocks with bullish and bearish signals and indicates the best insurance companies' stocks to trade:",

        'Interest Rates Forecast':
        "The Interest Rate Package includes predictions for various interest rates based on the I Know First algorithm.",

        'International Stocks':
        "This international stocks forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of international stocks with bullish and bearish signals:",

        'Israeli Stocks':
        "This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'Italian Stocks':
        "This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of Italian stocks with bullish and bearish signals:",

        'Medicine Stocks':
        "The Medicine Stocks Package is designed for investors and analysts who need predictions for the best stocks to buy in the Medicine Industry. It includes stocks with bullish and bearish signals and indicates the best medicine stocks to trade:",

        'Mega Cap Forecast':
        "This stock market forecast includes the best stocks determined by the algorithm with a market capitalization of more than $100 billion.",

        'MLP Stocks':
        "An MLP, or Master Limited Partnership, is a limited partnership that is publicly traded on a national securities exchange. MLPs are typically run by a general partner while a limited partner provides capital for the business. Generally, investors receive a stable yield on investments in MLPs with the opportunity to participate in business upside. This package provides algorithmic forecasts for MLP stocks based on market data.",

        'MSCI Stocks Universe':
        "This forecast is part of MSCI Stocks Universe Package and it is designed for investors and analysts who need predictions for MSCI ACWI stocks currently trading on Eastern stock markets, such as Japan, Singapore and Hong Kong. This forecast is part of the MSCI Eastern Stocks Subpackage, one of I Know First's algorithmic trading tools. The MSCI Stocks Unvierse is based on MSCI ACWI Index (part of the Modern Index Strategy) and captures all sources of equity returns in 23 developed and 24 emerging markets.",

        'Pharma Stocks Forecast':
        "This stock forecast is designed for investors and analysts who need predictions of the best stocks for the whole Pharmaceutical sector (see Pharma Stocks Package). It includes stocks with bullish and bearish signals and indicates the best pharmaceutical stocks to trade:",

        'Robinhood Trades':
        "This forecast is part of the Rabinhood Trades Package, one of I Know First's algorithmic trading tools. The full investment universe includes the most traded stocks by Robinhood stock trading platform users. Based on it, I Know First AI Algorithm identifies the most promising stocks and produces forecasts that include:",

        'S&P 100 Stocks':
        "This S&P 100 stocks forecast is designed for investors and analysts who need predictions for the best large cap performing stocks in the S&P100 Company Package (see S&P100 Stocks Package). It includes stocks with bullish and bearish signals and indicates the best S&P100 Companies stocks to buy:",

        'Saudi Arabian Stocks':
        "Best Saudi Arabian Stocks: This South African Stock forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes a daily prediction for a total of stocks with bullish and bearish signals:",

        'Small Cap Forecast':
        "The Small Cap Package includes recommendations by the I Know First algorithm for small cap stocks to buy with a market capitalization of less than $1 billion:",

        'South African Stocks':
        "Best South African Stocks: This South African Stock forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes a daily prediction for a total of stocks with bullish and bearish signals:",

        'Spanish Stocks':
        "This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of Spanish stocks with bullish and bearish signals:",

        'Stock Forecast & S&P500 Forecast':
        "This forecast is part of the S&P 500 Stocks Package, as one of I Know First's systematic trading tools. The full package includes a daily prediction for a total of stocks with bullish and bearish signals:",

        'Stocks Under $5':
        "This stock forecast is part of the Stocks Under 5 Dollars Package, as one of I Know First's algorithmic trading tools. The full package includes daily predictions for a total of 20 stocks with bullish and bearish signals:",

        'Stocks Under $50':
        "This forecast is part of the Stocks Under 50 Dollars Package, as one of I Know First's forecast services. The full package includes daily stock predictions for a total of 20 stocks with bullish and bearish signals:",

        'Stocks Under $20':
        "This forecast is part of the Stocks Under 20 Dollars Package, as one of I Know First's forecast services. The full package includes daily stock predictions for a total of 20 stocks with bullish and bearish signals:",

        'Stocks Under $10':
        "This forecast is part of the Stocks Under 10 Dollars Package, as one of I Know First's forecast services. The full package includes daily stock predictions for a total of 20 stocks with bullish and bearish signals:",

        'Swiss Stocks':
        "This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of Swiss stocks with bullish and bearish signals:",

        'Tech Stocks Forecast':
        "This Tech Stock forecast is based on stock picking strategies for investors and analysts who need predictions for the 10 best tech stocks in the Technology Industry (see Tech Stocks Package). It includes stocks with bullish and bearish signals:",

        'Transportation Stocks':
        "This Transportation Stocks forecast is designed for investors and analysts who need predictions for the best stocks to invest in the transport sectors (see Transportation Stocks Package). It includes stocks with bullish and bearish signals:",

        'Turkish Stock Forecast':
        "This forecast is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'UK Stock Forecast':
        "This forecast for UK Stocks is part of the By Country Package, as one of I Know First's neural network trading tools. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'US Sector Indices Forecast':
        "This algorithmic forecast is part of the US Sector Indices Package, as one of I Know First's quantitative investment solutions. We determine our US sector indices picks by screening our database daily using our advanced algorithm. The full US Sector Indices Package includes a daily forecast for a total of indices with bullish and bearish signals:",

        'Volatility Forecast':
        "Volatility Forecast: This Volatility forecast is designed for investors and analysts who need predictions of the implied volatility for a basket of put and call options related to a specific index. It includes 8 volatility indices with bullish and bearish signals and indicates the best Volatility Index to trade:",

        'S&P500 Companies':
        "This top S&P 500 stocks forecast is designed for investors and analysts who need predictions for the whole S&P 500 (See S&P 500 Companies Package). It includes stocks with bullish and bearish signals and indicates the best S&P 500 Companies stocks to buy:",

        'Warren Buffett Portfolio':
        "This Warren Buffett Stocks Portfolio is part of the Buffett's Top Stocks Package, as one of I Know First's quantitative investment solutions. Investors generally utilize the I Know First advanced self-learning algorithm to take advantage of Warren Buffett's proven investing strategy. The full Top Warren Buffett's Stocks Package includes the best stocks identified by the algorithm that are currently in Warren Buffett's portfolio:",

        'Apple Stock Forecasts':
        "This forecast is the Apple Stock forecast from Nov 15th, 2015 to Feb 15th, 2016",

        'Real Estate Stock Forecast':
        "This Real Estate Stocks forecast is designed for investors and analysts who need predictions for the best stocks to invest in the real estate sector (see Real Estate Stocks Package). It includes stocks with bullish and bearish signals:",

        'Tech Giants Stocks Forecast':
        "This Tech Giants Stocks forecast is designed for investors and analysts who need predictions for the best stocks to invest in the Tech Giants sector (see Tech Giants Stocks Package). It includes stocks with bullish and bearish signals:",

        'Singaporean Stock Forecast':
        "This forecast for Singaporean Stocks is part of the By Country Package, as one of I Know First's neural network trading tools. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'Taiwanese Stock Forecast':
        "This forecast for Taiwanese Stocks is part of the By Country Package, as one of I Know First's neural network trading tools. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'Shenzhen Stock Forecast':
        "This forecast for Shenzen Stocks is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

        'Shanghai Stock Forecast':
        "This forecast for Shanghai Stocks is part of the By Country Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of stocks with bullish and bearish signals:",

    }

    for key, value in dict.items():
        if key == package_name:
            return value
    return "This forecast is part of the PACKAGE_CATEGORY Package, as one of I Know First's algorithmic trading tools. The full forecast includes daily predictions for a total of 20 stocks with bullish and bearish signals:"



























#
